export const cropData = {
  en: [
    {
      name: "Wheat",
      icon: "🌾",
      growingSeason: "October to May (Winter wheat) or March to August (Spring wheat)",
      wateringNeeds: "Medium",
      temperature: "15-25°C optimal, can tolerate -10°C to 35°C",
      commonDiseases: ["Rust", "Powdery Mildew", "Septoria", "Fusarium"],
      tips: [
        "Plant in well-drained soil with pH 6.0-7.5",
        "Ensure adequate nitrogen during tillering stage",
        "Monitor for pest infestations regularly",
        "Harvest when moisture content is 12-14%",
      ],
    },
    {
      name: "Tomato",
      icon: "🍅",
      growingSeason: "March to June (planting), June to October (harvest)",
      wateringNeeds: "High",
      temperature: "18-25°C optimal, sensitive to frost",
      commonDiseases: ["Blight", "Mosaic Virus", "Bacterial Wilt", "Fusarium Wilt"],
      tips: [
        "Provide support structures for indeterminate varieties",
        "Water consistently to prevent blossom end rot",
        "Mulch around plants to retain moisture",
        "Prune suckers for better fruit development",
      ],
    },
    {
      name: "Cotton",
      icon: "🌱",
      growingSeason: "April to October",
      wateringNeeds: "High",
      temperature: "20-30°C optimal, requires warm climate",
      commonDiseases: ["Bollworm", "Verticillium Wilt", "Bacterial Blight", "Root Rot"],
      tips: [
        "Plant after soil temperature reaches 18°C",
        "Maintain consistent moisture during flowering",
        "Monitor for bollworm and apply IPM strategies",
        "Harvest when bolls are fully opened",
      ],
    },
    {
      name: "Corn",
      icon: "🌽",
      growingSeason: "April to September",
      wateringNeeds: "Medium",
      temperature: "16-35°C, requires warm growing season",
      commonDiseases: ["Corn Borer", "Gray Leaf Spot", "Northern Corn Leaf Blight", "Smut"],
      tips: [
        "Plant in blocks for better pollination",
        "Side-dress with nitrogen at knee-high stage",
        "Ensure adequate water during tasseling",
        "Harvest when kernels are at 20-25% moisture",
      ],
    },
    {
      name: "Rice",
      icon: "🌾",
      growingSeason: "May to October",
      wateringNeeds: "High",
      temperature: "20-35°C, requires consistent warmth",
      commonDiseases: ["Blast", "Bacterial Leaf Blight", "Sheath Blight", "Brown Spot"],
      tips: [
        "Maintain 2-5cm water depth in flooded fields",
        "Transplant seedlings at 20-25 days old",
        "Apply nitrogen in split doses",
        "Drain fields 2 weeks before harvest",
      ],
    },
    {
      name: "Potato",
      icon: "🥔",
      growingSeason: "March to June (planting), June to September (harvest)",
      wateringNeeds: "Medium",
      temperature: "15-20°C optimal, cool season crop",
      commonDiseases: ["Late Blight", "Early Blight", "Potato Scab", "Blackleg"],
      tips: [
        "Plant in well-drained, loose soil",
        "Hill soil around plants as they grow",
        "Avoid overwatering to prevent rot",
        "Harvest after foliage dies back naturally",
      ],
    },
  ],
  uz: [
    {
      name: "Bug'doy",
      icon: "🌾",
      growingSeason: "Oktyabr-May (qishki bug'doy) yoki Mart-Avgust (yazoqi bug'doy)",
      wateringNeeds: "O'rta",
      temperature: "15-25°C optimal, -10°C dan 35°C gacha chidaydi",
      commonDiseases: ["Zang", "Oq chang", "Septoriya", "Fuzarium"],
      tips: [
        "pH 6.0-7.5 bo'lgan yaxshi drenajli tuproqqa eking",
        "Butalashtirish bosqichida etarli azot ta'minlang",
        "Zararkunandalar invaziyasini muntazam kuzatib boring",
        "Namlik 12-14% bo'lganda yig'ib oling",
      ],
    },
    {
      name: "Pomidor",
      icon: "🍅",
      growingSeason: "Mart-Iyun (ekish), Iyun-Oktyabr (hosil)",
      wateringNeeds: "Yuqori",
      temperature: "18-25°C optimal, sovuqqa sezgir",
      commonDiseases: ["Fitoftora", "Mozaika virusi", "Bakterial so'lish", "Fuzarium so'lishi"],
      tips: [
        "Aniq navlar uchun tayanch tuzilmalarini ta'minlang",
        "Gul uchining chirishini oldini olish uchun muntazam sug'oring",
        "Namlikni saqlash uchun o'simlik atrofini mulchalang",
        "Yaxshi meva rivojlanishi uchun yon kurtaklarni kesing",
      ],
    },
    {
      name: "Paxta",
      icon: "🌱",
      growingSeason: "Aprel-Oktyabr",
      wateringNeeds: "Yuqori",
      temperature: "20-30°C optimal, issiq iqlim talab qiladi",
      commonDiseases: ["Paxta qurti", "Vertisillyum so'lishi", "Bakterial yanglish", "Ildiz chirishi"],
      tips: [
        "Tuproq harorati 18°C ga yetgandan keyin eking",
        "Gullashtirish paytida doimiy namlikni saqlang",
        "Paxta qurtini kuzatib boring va IPM strategiyalarini qo'llang",
        "Kapsulalar to'liq ochilganda yig'ib oling",
      ],
    },
    {
      name: "Makkajo'xori",
      icon: "🌽",
      growingSeason: "Aprel-Sentyabr",
      wateringNeeds: "O'rta",
      temperature: "16-35°C, issiq o'sish mavsumi talab qiladi",
      commonDiseases: ["Makkajo'xori quriti", "Kulrang dog'", "Shimoliy barg yanglishi", "Qora chang"],
      tips: [
        "Yaxshi changlanish uchun bloklar shaklida eking",
        "Tiz balandligida azot bilan qo'shimcha oziqlantirishni amalga oshiring",
        "Changlanish paytida etarli suv ta'minlang",
        "Donlar 20-25% namlikda bo'lganda yig'ib oling",
      ],
    },
    {
      name: "Sholi",
      icon: "🌾",
      growingSeason: "May-Oktyabr",
      wateringNeeds: "Yuqori",
      temperature: "20-35°C, doimiy issiqlik talab qiladi",
      commonDiseases: ["Portlash", "Bakterial barg yanglishi", "Qin yanglishi", "Jigarrang dog'"],
      tips: [
        "Suv bosgan dalalarda 2-5sm suv chuqurligini saqlang",
        "Ko'chatlarni 20-25 kunlikda ko'chiring",
        "Azotni bo'lib-bo'lib qo'llang",
        "Hosil olishdan 2 hafta oldin dalalarni quritib qo'ying",
      ],
    },
    {
      name: "Kartoshka",
      icon: "🥔",
      growingSeason: "Mart-Iyun (ekish), Iyun-Sentyabr (hosil)",
      wateringNeeds: "O'rta",
      temperature: "15-20°C optimal, sovuq mavsum ekinlari",
      commonDiseases: ["Kech fitoftora", "Erta fitoftora", "Kartoshka qoraqo'tiri", "Qora oyoq"],
      tips: [
        "Yaxshi drenajli, yumshoq tuproqqa eking",
        "O'simliklar o'sishi bilan tuproqni tepaga to'plang",
        "Chirishni oldini olish uchun ortiqcha sug'orishdan saqlaning",
        "Barglar tabiiy ravishda qurigandan keyin yig'ib oling",
      ],
    },
  ],
}
