export const marketData = {
  en: [
    {
      name: "Wheat",
      icon: "🌾",
      category: "Grains",
      price: 0.25,
      change: 0.02,
      trend: "up" as const,
    },
    {
      name: "Corn",
      icon: "🌽",
      category: "Grains",
      price: 0.22,
      change: -0.01,
      trend: "down" as const,
    },
    {
      name: "Rice",
      icon: "🍚",
      category: "Grains",
      price: 0.45,
      change: 0.0,
      trend: "stable" as const,
    },
    {
      name: "Cotton",
      icon: "🌱",
      category: "Cash Crops",
      price: 1.85,
      change: 0.15,
      trend: "up" as const,
    },
    {
      name: "Tomatoes",
      icon: "🍅",
      category: "Vegetables",
      price: 2.5,
      change: -0.25,
      trend: "down" as const,
    },
    {
      name: "Potatoes",
      icon: "🥔",
      category: "Vegetables",
      price: 0.8,
      change: 0.05,
      trend: "up" as const,
    },
    {
      name: "Soybeans",
      icon: "🫘",
      category: "Legumes",
      price: 0.35,
      change: 0.03,
      trend: "up" as const,
    },
    {
      name: "Onions",
      icon: "🧅",
      category: "Vegetables",
      price: 1.2,
      change: -0.1,
      trend: "down" as const,
    },
    {
      name: "Carrots",
      icon: "🥕",
      category: "Vegetables",
      price: 1.5,
      change: 0.0,
      trend: "stable" as const,
    },
  ],
  uz: [
    {
      name: "Bug'doy",
      icon: "🌾",
      category: "Don ekinlari",
      price: 0.25,
      change: 0.02,
      trend: "up" as const,
    },
    {
      name: "Makkajo'xori",
      icon: "🌽",
      category: "Don ekinlari",
      price: 0.22,
      change: -0.01,
      trend: "down" as const,
    },
    {
      name: "Sholi",
      icon: "🍚",
      category: "Don ekinlari",
      price: 0.45,
      change: 0.0,
      trend: "stable" as const,
    },
    {
      name: "Paxta",
      icon: "🌱",
      category: "Texnik ekinlar",
      price: 1.85,
      change: 0.15,
      trend: "up" as const,
    },
    {
      name: "Pomidor",
      icon: "🍅",
      category: "Sabzavotlar",
      price: 2.5,
      change: -0.25,
      trend: "down" as const,
    },
    {
      name: "Kartoshka",
      icon: "🥔",
      category: "Sabzavotlar",
      price: 0.8,
      change: 0.05,
      trend: "up" as const,
    },
    {
      name: "Soya",
      icon: "🫘",
      category: "Dukkakli ekinlar",
      price: 0.35,
      change: 0.03,
      trend: "up" as const,
    },
    {
      name: "Piyoz",
      icon: "🧅",
      category: "Sabzavotlar",
      price: 1.2,
      change: -0.1,
      trend: "down" as const,
    },
    {
      name: "Sabzi",
      icon: "🥕",
      category: "Sabzavotlar",
      price: 1.5,
      change: 0.0,
      trend: "stable" as const,
    },
  ],
}
